# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditLimitGui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(782, 389)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 0, 5, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.hardwareEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hardwareEdit.setObjectName("hardwareEdit")
        self.gridLayout.addWidget(self.hardwareEdit, 2, 1, 1, 1)
        self.categoryEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.categoryEdit.setObjectName("categoryEdit")
        self.gridLayout.addWidget(self.categoryEdit, 1, 1, 1, 1)
        self.standardEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.standardEdit.setObjectName("standardEdit")
        self.gridLayout.addWidget(self.standardEdit, 0, 1, 1, 1)
        self.categoryBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.categoryBox.setObjectName("categoryBox")
        self.gridLayout.addWidget(self.categoryBox, 1, 0, 1, 1)
        self.standardBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.standardBox.setObjectName("standardBox")
        self.gridLayout.addWidget(self.standardBox, 0, 0, 1, 1)
        self.hardwareBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.hardwareBox.setObjectName("hardwareBox")
        self.gridLayout.addWidget(self.hardwareBox, 2, 0, 1, 1)
        self.delStandardButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delStandardButton.setObjectName("delStandardButton")
        self.gridLayout.addWidget(self.delStandardButton, 0, 2, 1, 1)
        self.delCategoryButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delCategoryButton.setObjectName("delCategoryButton")
        self.gridLayout.addWidget(self.delCategoryButton, 1, 2, 1, 1)
        self.delHardwareButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delHardwareButton.setObjectName("delHardwareButton")
        self.gridLayout.addWidget(self.delHardwareButton, 2, 2, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 100)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 350, 251, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.okButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 190, 761, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.limitsLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.limitsLayout.setContentsMargins(0, 0, 0, 0)
        self.limitsLayout.setHorizontalSpacing(5)
        self.limitsLayout.setObjectName("limitsLayout")
        self.parameterBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.parameterBox.setObjectName("parameterBox")
        self.limitsLayout.addWidget(self.parameterBox, 0, 0, 1, 2)
        self.removeButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.removeButton.setObjectName("removeButton")
        self.limitsLayout.addWidget(self.removeButton, 1, 1, 1, 1)
        self.limitsTable = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.limitsTable.setRowCount(1)
        self.limitsTable.setColumnCount(3)
        self.limitsTable.setObjectName("limitsTable")
        self.limitsTable.horizontalHeader().setVisible(True)
        self.limitsTable.horizontalHeader().setCascadingSectionResizes(False)
        self.limitsTable.verticalHeader().setVisible(False)
        self.limitsLayout.addWidget(self.limitsTable, 0, 2, 2, 1)
        self.addButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.addButton.setObjectName("addButton")
        self.limitsLayout.addWidget(self.addButton, 1, 0, 1, 1)
        self.exampleTable = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.exampleTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.exampleTable.setRowCount(1)
        self.exampleTable.setColumnCount(11)
        self.exampleTable.setObjectName("exampleTable")
        self.exampleTable.verticalHeader().setVisible(False)
        self.limitsLayout.addWidget(self.exampleTable, 0, 3, 2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit Limits"))
        self.delStandardButton.setText(_translate("Dialog", "Delete"))
        self.delCategoryButton.setText(_translate("Dialog", "Delete"))
        self.delHardwareButton.setText(_translate("Dialog", "Delete"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.okButton.setText(_translate("Dialog", "Ok"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.removeButton.setText(_translate("Dialog", "Remove"))
        self.addButton.setText(_translate("Dialog", "Add"))

