# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'embedWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(797, 320)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plugVerticalLayout = QtWidgets.QVBoxLayout()
        self.plugVerticalLayout.setObjectName("plugVerticalLayout")
        self.plugGroupBox = QtWidgets.QGroupBox(Form)
        self.plugGroupBox.setObjectName("plugGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.plugGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.plugList = QtWidgets.QComboBox(self.plugGroupBox)
        self.plugList.setObjectName("plugList")
        self.horizontalLayout_4.addWidget(self.plugList)
        self.plugVerticalLayout.addWidget(self.plugGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 149, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.plugVerticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.plugVerticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.reverseLayoutBox = QtWidgets.QHBoxLayout()
        self.reverseLayoutBox.setObjectName("reverseLayoutBox")
        self.reverseCheckBox = QtWidgets.QCheckBox(Form)
        self.reverseCheckBox.setObjectName("reverseCheckBox")
        self.reverseLayoutBox.addWidget(self.reverseCheckBox)
        self.verticalLayout_2.addLayout(self.reverseLayoutBox)
        self.matedMeasurementsVerticalLayout = QtWidgets.QVBoxLayout()
        self.matedMeasurementsVerticalLayout.setObjectName("matedMeasurementsVerticalLayout")
        self.matedMeasurementsGroupBox = QtWidgets.QGroupBox(Form)
        self.matedMeasurementsGroupBox.setObjectName("matedMeasurementsGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.matedMeasurementsGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.openLabel = QtWidgets.QLabel(self.matedMeasurementsGroupBox)
        self.openLabel.setObjectName("openLabel")
        self.horizontalLayout_5.addWidget(self.openLabel)
        self.importOpen = QtWidgets.QPushButton(self.matedMeasurementsGroupBox)
        self.importOpen.setObjectName("importOpen")
        self.horizontalLayout_5.addWidget(self.importOpen)
        self.acquireOpen = QtWidgets.QPushButton(self.matedMeasurementsGroupBox)
        self.acquireOpen.setObjectName("acquireOpen")
        self.horizontalLayout_5.addWidget(self.acquireOpen)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.openFileName = QtWidgets.QLabel(self.matedMeasurementsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.openFileName.setFont(font)
        self.openFileName.setObjectName("openFileName")
        self.verticalLayout_4.addWidget(self.openFileName)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.shortLabel = QtWidgets.QLabel(self.matedMeasurementsGroupBox)
        self.shortLabel.setObjectName("shortLabel")
        self.horizontalLayout_6.addWidget(self.shortLabel)
        self.importShort = QtWidgets.QPushButton(self.matedMeasurementsGroupBox)
        self.importShort.setObjectName("importShort")
        self.horizontalLayout_6.addWidget(self.importShort)
        self.acquireShort = QtWidgets.QPushButton(self.matedMeasurementsGroupBox)
        self.acquireShort.setObjectName("acquireShort")
        self.horizontalLayout_6.addWidget(self.acquireShort)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.shortFileName = QtWidgets.QLabel(self.matedMeasurementsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.shortFileName.setFont(font)
        self.shortFileName.setObjectName("shortFileName")
        self.verticalLayout_4.addWidget(self.shortFileName)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.loadLabel = QtWidgets.QLabel(self.matedMeasurementsGroupBox)
        self.loadLabel.setObjectName("loadLabel")
        self.horizontalLayout_7.addWidget(self.loadLabel)
        self.importLoad = QtWidgets.QPushButton(self.matedMeasurementsGroupBox)
        self.importLoad.setObjectName("importLoad")
        self.horizontalLayout_7.addWidget(self.importLoad)
        self.acquireLoad = QtWidgets.QPushButton(self.matedMeasurementsGroupBox)
        self.acquireLoad.setObjectName("acquireLoad")
        self.horizontalLayout_7.addWidget(self.acquireLoad)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.loadFileName = QtWidgets.QLabel(self.matedMeasurementsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loadFileName.setFont(font)
        self.loadFileName.setObjectName("loadFileName")
        self.verticalLayout_4.addWidget(self.loadFileName)
        self.matedMeasurementsVerticalLayout.addWidget(self.matedMeasurementsGroupBox)
        self.verticalLayout_2.addLayout(self.matedMeasurementsVerticalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.categoryLayout = QtWidgets.QVBoxLayout()
        self.categoryLayout.setObjectName("categoryLayout")
        self.categoryGroupBox = QtWidgets.QGroupBox(Form)
        self.categoryGroupBox.setObjectName("categoryGroupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.categoryGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.embedCat6 = QtWidgets.QRadioButton(self.categoryGroupBox)
        self.embedCat6.setObjectName("embedCat6")
        self.verticalLayout_8.addWidget(self.embedCat6)
        self.embedCat5 = QtWidgets.QRadioButton(self.categoryGroupBox)
        self.embedCat5.setObjectName("embedCat5")
        self.verticalLayout_8.addWidget(self.embedCat5)
        self.categoryLayout.addWidget(self.categoryGroupBox)
        self.verticalLayout_3.addLayout(self.categoryLayout)
        self.reembedButtonLayout = QtWidgets.QVBoxLayout()
        self.reembedButtonLayout.setObjectName("reembedButtonLayout")
        self.reembedButton = QtWidgets.QPushButton(Form)
        self.reembedButton.setObjectName("reembedButton")
        self.reembedButtonLayout.addWidget(self.reembedButton)
        self.verticalLayout_3.addLayout(self.reembedButtonLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plugGroupBox.setTitle(_translate("Form", "Plug"))
        self.reverseCheckBox.setText(_translate("Form", "Reverse"))
        self.matedMeasurementsGroupBox.setTitle(_translate("Form", "Mated measurements"))
        self.openLabel.setText(_translate("Form", "Open:"))
        self.importOpen.setText(_translate("Form", "Import SNP"))
        self.acquireOpen.setText(_translate("Form", "Acquire"))
        self.openFileName.setText(_translate("Form", "\"\""))
        self.shortLabel.setText(_translate("Form", "Short:"))
        self.importShort.setText(_translate("Form", "Import SNP"))
        self.acquireShort.setText(_translate("Form", "Acquire"))
        self.shortFileName.setText(_translate("Form", "\"\""))
        self.loadLabel.setText(_translate("Form", "Load:"))
        self.importLoad.setText(_translate("Form", "Import SNP"))
        self.acquireLoad.setText(_translate("Form", "Acquire"))
        self.loadFileName.setText(_translate("Form", "\"\""))
        self.categoryGroupBox.setTitle(_translate("Form", "Category"))
        self.embedCat6.setText(_translate("Form", "Cat 6/6A"))
        self.embedCat5.setText(_translate("Form", "Cat 5"))
        self.reembedButton.setText(_translate("Form", "Reemebed"))

