# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 683)
        MainWindow.setMinimumSize(QtCore.QSize(896, 683))
        MainWindow.setWindowOpacity(42.0)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setHandleWidth(10)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.sampleTable = QtWidgets.QTableWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleTable.sizePolicy().hasHeightForWidth())
        self.sampleTable.setSizePolicy(sizePolicy)
        self.sampleTable.setMinimumSize(QtCore.QSize(50, 507))
        self.sampleTable.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sampleTable.setAlternatingRowColors(True)
        self.sampleTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sampleTable.setObjectName("sampleTable")
        self.sampleTable.setColumnCount(0)
        self.sampleTable.setRowCount(0)
        self.sampleTable.horizontalHeader().setVisible(True)
        self.sampleTable.verticalHeader().setVisible(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.verticalLayoutWidget)
        self.splitter.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(10)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.graphicsView = Canvas(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 250))
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setObjectName("graphicsView")
        self.param_tabs = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.param_tabs.sizePolicy().hasHeightForWidth())
        self.param_tabs.setSizePolicy(sizePolicy)
        self.param_tabs.setObjectName("param_tabs")
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout_4.addWidget(self.splitter_2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar2.setMovable(False)
        self.toolBar2.setObjectName("toolBar2")
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar2)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.toolBar.setFont(font)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 896, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuVNA = QtWidgets.QMenu(self.menuBar)
        self.menuVNA.setObjectName("menuVNA")
        MainWindow.setMenuBar(self.menuBar)
        self.actionImport_SnP = QtWidgets.QAction(MainWindow)
        self.actionImport_SnP.setObjectName("actionImport_SnP")
        self.actionImport_Project = QtWidgets.QAction(MainWindow)
        self.actionImport_Project.setCheckable(False)
        self.actionImport_Project.setChecked(False)
        self.actionImport_Project.setObjectName("actionImport_Project")
        self.actionSave_Project = QtWidgets.QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionExport_Excel = QtWidgets.QAction(MainWindow)
        self.actionExport_Excel.setObjectName("actionExport_Excel")
        self.actionGenerate_Report = QtWidgets.QAction(MainWindow)
        self.actionGenerate_Report.setObjectName("actionGenerate_Report")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionConfigure_Test = QtWidgets.QAction(MainWindow)
        self.actionConfigure_Test.setObjectName("actionConfigure_Test")
        self.actionConnect_to_VNA = QtWidgets.QAction(MainWindow)
        self.actionConnect_to_VNA.setObjectName("actionConnect_to_VNA")
        self.actionConfigure_Reports = QtWidgets.QAction(MainWindow)
        self.actionConfigure_Reports.setObjectName("actionConfigure_Reports")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionImport_Snp = QtWidgets.QAction(MainWindow)
        self.actionImport_Snp.setCheckable(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pictures/Icons/ImportFile2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport_Snp.setIcon(icon)
        self.actionImport_Snp.setObjectName("actionImport_Snp")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pictures/Icons/newProject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Project.setIcon(icon1)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionWho_am_I = QtWidgets.QAction(MainWindow)
        self.actionWho_am_I.setObjectName("actionWho_am_I")
        self.actionAquire = QtWidgets.QAction(MainWindow)
        self.actionAquire.setObjectName("actionAquire")
        self.actionCalibrate = QtWidgets.QAction(MainWindow)
        self.actionCalibrate.setObjectName("actionCalibrate")
        self.toolBar.addAction(self.actionNew_Project)
        self.toolBar.addAction(self.actionImport_Snp)
        self.menuFile.addAction(self.actionImport_Project)
        self.menuFile.addAction(self.actionImport_SnP)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Excel)
        self.menuFile.addAction(self.actionGenerate_Report)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuSettings.addAction(self.actionConfigure_Test)
        self.menuSettings.addAction(self.actionConfigure_Reports)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionTest)
        self.menuVNA.addAction(self.actionConnect)
        self.menuVNA.addSeparator()
        self.menuVNA.addAction(self.actionAquire)
        self.menuVNA.addAction(self.actionCalibrate)
        self.menuVNA.addSeparator()
        self.menuVNA.addAction(self.actionWho_am_I)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuVNA.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.actionImport_Snp.triggered.connect(MainWindow.importSnp)
        self.actionNew_Project.triggered.connect(MainWindow.newProject)
        self.sampleTable.itemSelectionChanged.connect(MainWindow.setActiveSample)
        self.param_tabs.currentChanged['int'].connect(MainWindow.tabChange)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Belden Network Analyzer Software "))
        self.toolBar2.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuVNA.setTitle(_translate("MainWindow", "VNA"))
        self.actionImport_SnP.setText(_translate("MainWindow", "Import SnP"))
        self.actionImport_Project.setText(_translate("MainWindow", "Import Project"))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project"))
        self.actionExport_Excel.setText(_translate("MainWindow", "Export Excel"))
        self.actionGenerate_Report.setText(_translate("MainWindow", "Generate Report"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionConfigure_Test.setText(_translate("MainWindow", "Configure Test"))
        self.actionConnect_to_VNA.setText(_translate("MainWindow", "Connect"))
        self.actionConfigure_Reports.setText(_translate("MainWindow", "Configure Reports"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.actionImport_Snp.setText(_translate("MainWindow", "Import Snp"))
        self.actionImport_Snp.setToolTip(_translate("MainWindow", "Import SnP file"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionNew_Project.setToolTip(_translate("MainWindow", "Create New Project"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionWho_am_I.setText(_translate("MainWindow", "Who am I ?"))
        self.actionAquire.setText(_translate("MainWindow", "Measure"))
        self.actionCalibrate.setText(_translate("MainWindow", "Calibrate"))

from canvas import Canvas
