# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(820, 526)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(12, 12, 788, 502))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.df_open_import = QtWidgets.QPushButton(self.groupBox)
        self.df_open_import.setObjectName("df_open_import")
        self.horizontalLayout.addWidget(self.df_open_import)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.df_open_acquire = QtWidgets.QPushButton(self.groupBox)
        self.df_open_acquire.setObjectName("df_open_acquire")
        self.horizontalLayout.addWidget(self.df_open_acquire)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.df_open_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.df_open_label.setFont(font)
        self.df_open_label.setObjectName("df_open_label")
        self.verticalLayout_3.addWidget(self.df_open_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.df_short_import = QtWidgets.QPushButton(self.groupBox)
        self.df_short_import.setObjectName("df_short_import")
        self.horizontalLayout_2.addWidget(self.df_short_import)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.df_short_acquire = QtWidgets.QPushButton(self.groupBox)
        self.df_short_acquire.setObjectName("df_short_acquire")
        self.horizontalLayout_2.addWidget(self.df_short_acquire)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.df_short_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.df_short_label.setFont(font)
        self.df_short_label.setObjectName("df_short_label")
        self.verticalLayout_3.addWidget(self.df_short_label)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.pdf_open_import = QtWidgets.QPushButton(self.groupBox_2)
        self.pdf_open_import.setObjectName("pdf_open_import")
        self.horizontalLayout_5.addWidget(self.pdf_open_import)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.pdf_open_acquire = QtWidgets.QPushButton(self.groupBox_2)
        self.pdf_open_acquire.setObjectName("pdf_open_acquire")
        self.horizontalLayout_5.addWidget(self.pdf_open_acquire)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.pdf_open_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pdf_open_label.setFont(font)
        self.pdf_open_label.setObjectName("pdf_open_label")
        self.verticalLayout_6.addWidget(self.pdf_open_label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.pdf_short_import = QtWidgets.QPushButton(self.groupBox_2)
        self.pdf_short_import.setObjectName("pdf_short_import")
        self.horizontalLayout_6.addWidget(self.pdf_short_import)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.pdf_short_acquire = QtWidgets.QPushButton(self.groupBox_2)
        self.pdf_short_acquire.setObjectName("pdf_short_acquire")
        self.horizontalLayout_6.addWidget(self.pdf_short_acquire)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.pdf_short_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pdf_short_label.setFont(font)
        self.pdf_short_label.setObjectName("pdf_short_label")
        self.verticalLayout_6.addWidget(self.pdf_short_label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.pdf_load_import = QtWidgets.QPushButton(self.groupBox_2)
        self.pdf_load_import.setObjectName("pdf_load_import")
        self.horizontalLayout_7.addWidget(self.pdf_load_import)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.pdf_load_acquire = QtWidgets.QPushButton(self.groupBox_2)
        self.pdf_load_acquire.setObjectName("pdf_load_acquire")
        self.horizontalLayout_7.addWidget(self.pdf_load_acquire)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.pdf_load_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pdf_load_label.setFont(font)
        self.pdf_load_label.setObjectName("pdf_load_label")
        self.verticalLayout_6.addWidget(self.pdf_load_label)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.plug_name_line_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.plug_name_line_edit.setObjectName("plug_name_line_edit")
        self.horizontalLayout_8.addWidget(self.plug_name_line_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_9.addWidget(self.cancelButton)
        self.addPlug = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addPlug.setObjectName("addPlug")
        self.horizontalLayout_9.addWidget(self.addPlug)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.graphicsView = Canvas(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(500, 500))
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_4.addWidget(self.graphicsView)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Direct Fixture"))
        self.label.setText(_translate("Dialog", "Open"))
        self.df_open_import.setText(_translate("Dialog", "Import"))
        self.label_2.setText(_translate("Dialog", "or"))
        self.df_open_acquire.setText(_translate("Dialog", "Acquire"))
        self.df_open_label.setText(_translate("Dialog", "\"\""))
        self.label_3.setText(_translate("Dialog", "Short"))
        self.df_short_import.setText(_translate("Dialog", "Import"))
        self.label_4.setText(_translate("Dialog", "or"))
        self.df_short_acquire.setText(_translate("Dialog", "Acquire"))
        self.df_short_label.setText(_translate("Dialog", "\"\""))
        self.groupBox_2.setTitle(_translate("Dialog", "Plug + Direct Fixture"))
        self.label_9.setText(_translate("Dialog", "Open"))
        self.pdf_open_import.setText(_translate("Dialog", "Import"))
        self.label_10.setText(_translate("Dialog", "or"))
        self.pdf_open_acquire.setText(_translate("Dialog", "Acquire"))
        self.pdf_open_label.setText(_translate("Dialog", "\"\""))
        self.label_11.setText(_translate("Dialog", "Short"))
        self.pdf_short_import.setText(_translate("Dialog", "Import"))
        self.label_12.setText(_translate("Dialog", "or"))
        self.pdf_short_acquire.setText(_translate("Dialog", "Acquire"))
        self.pdf_short_label.setText(_translate("Dialog", "\"\""))
        self.label_13.setText(_translate("Dialog", "Load"))
        self.pdf_load_import.setText(_translate("Dialog", "Import"))
        self.label_14.setText(_translate("Dialog", "or"))
        self.pdf_load_acquire.setText(_translate("Dialog", "Acquire"))
        self.pdf_load_label.setText(_translate("Dialog", "\"\""))
        self.label_15.setText(_translate("Dialog", "Plug Name:"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.addPlug.setText(_translate("Dialog", "Add"))

from canvas import Canvas
