# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis\plugImportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlugImportDialog(object):
    def setupUi(self, PlugImportDialog):
        PlugImportDialog.setObjectName("PlugImportDialog")
        PlugImportDialog.resize(452, 345)
        self.buttonBox = QtWidgets.QDialogButtonBox(PlugImportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 300, 401, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(PlugImportDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 431, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.dfOpenBtn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.dfOpenBtn.setObjectName("dfOpenBtn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dfOpenBtn)
        self.dfShortBtn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.dfShortBtn.setObjectName("dfShortBtn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dfShortBtn)
        self.dfOpenLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.dfOpenLabel.setText("")
        self.dfOpenLabel.setObjectName("dfOpenLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dfOpenLabel)
        self.dfShortLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.dfShortLabel.setText("")
        self.dfShortLabel.setObjectName("dfShortLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dfShortLabel)
        self.label_3 = QtWidgets.QLabel(PlugImportDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(PlugImportDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayoutWidget_2 = QtWidgets.QWidget(PlugImportDialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 120, 431, 180))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.openBtn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.openBtn.setObjectName("openBtn")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.openBtn)
        self.openLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.openLabel.setText("")
        self.openLabel.setObjectName("openLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.openLabel)
        self.shortBtn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.shortBtn.setObjectName("shortBtn")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.shortBtn)
        self.shortLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.shortLabel.setText("")
        self.shortLabel.setObjectName("shortLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shortLabel)
        self.loadBtn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.loadBtn.setObjectName("loadBtn")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.loadBtn)
        self.sJ124578Label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.sJ124578Label.setObjectName("sJ124578Label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sJ124578Label)
        self.sJ12LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.sJ12LineEdit.setObjectName("sJ12LineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sJ12LineEdit)
        self.sJ36Label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.sJ36Label.setObjectName("sJ36Label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sJ36Label)
        self.sJ36LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.sJ36LineEdit.setObjectName("sJ36LineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sJ36LineEdit)
        self.thruCalibLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.thruCalibLabel.setObjectName("thruCalibLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.thruCalibLabel)
        self.thruCalibLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.thruCalibLineEdit.setObjectName("thruCalibLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.thruCalibLineEdit)
        self.loadLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.loadLabel.setText("")
        self.loadLabel.setObjectName("loadLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.loadLabel)

        self.retranslateUi(PlugImportDialog)
        self.buttonBox.rejected.connect(PlugImportDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PlugImportDialog)

    def retranslateUi(self, PlugImportDialog):
        _translate = QtCore.QCoreApplication.translate
        PlugImportDialog.setWindowTitle(_translate("PlugImportDialog", "Import Plug SNPs"))
        self.dfOpenBtn.setText(_translate("PlugImportDialog", "Import Open"))
        self.dfShortBtn.setText(_translate("PlugImportDialog", "Import Short"))
        self.label_3.setText(_translate("PlugImportDialog", "Direct Fixture"))
        self.label_4.setText(_translate("PlugImportDialog", "Direct Fixture + Plug"))
        self.openBtn.setText(_translate("PlugImportDialog", "Import Open"))
        self.shortBtn.setText(_translate("PlugImportDialog", "Import Short"))
        self.loadBtn.setText(_translate("PlugImportDialog", "Import Load"))
        self.sJ124578Label.setText(_translate("PlugImportDialog", "SJ 12,45,78"))
        self.sJ36Label.setText(_translate("PlugImportDialog", "SJ 36"))
        self.thruCalibLabel.setText(_translate("PlugImportDialog", "Thru Calib"))

