# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/compilation_configuration.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(707, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.presetsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.presetsHorizontalLayout.setObjectName("presetsHorizontalLayout")
        self.presetsLabel = QtWidgets.QLabel(form)
        self.presetsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.presetsLabel.setObjectName("presetsLabel")
        self.presetsHorizontalLayout.addWidget(self.presetsLabel)
        self.presetsComboBox = QtWidgets.QComboBox(form)
        self.presetsComboBox.setFrame(True)
        self.presetsComboBox.setObjectName("presetsComboBox")
        self.presetsHorizontalLayout.addWidget(self.presetsComboBox)
        self.presetsAddPushButton = QtWidgets.QPushButton(form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presetsAddPushButton.sizePolicy().hasHeightForWidth())
        self.presetsAddPushButton.setSizePolicy(sizePolicy)
        self.presetsAddPushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.presetsAddPushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.presetsAddPushButton.setBaseSize(QtCore.QSize(0, 0))
        self.presetsAddPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/plus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.presetsAddPushButton.setIcon(icon)
        self.presetsAddPushButton.setFlat(True)
        self.presetsAddPushButton.setObjectName("presetsAddPushButton")
        self.presetsHorizontalLayout.addWidget(self.presetsAddPushButton)
        self.presetsRemovePushButton = QtWidgets.QPushButton(form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presetsRemovePushButton.sizePolicy().hasHeightForWidth())
        self.presetsRemovePushButton.setSizePolicy(sizePolicy)
        self.presetsRemovePushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.presetsRemovePushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.presetsRemovePushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/minus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.presetsRemovePushButton.setIcon(icon1)
        self.presetsRemovePushButton.setFlat(True)
        self.presetsRemovePushButton.setObjectName("presetsRemovePushButton")
        self.presetsHorizontalLayout.addWidget(self.presetsRemovePushButton)
        self.verticalLayout.addLayout(self.presetsHorizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.mainHorizontalLayout = QtWidgets.QHBoxLayout()
        self.mainHorizontalLayout.setObjectName("mainHorizontalLayout")
        self.configGridLayout = QtWidgets.QGridLayout()
        self.configGridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.configGridLayout.setObjectName("configGridLayout")
        self.parameterComboBox = QtWidgets.QComboBox(form)
        self.parameterComboBox.setObjectName("parameterComboBox")
        self.configGridLayout.addWidget(self.parameterComboBox, 1, 1, 1, 1)
        self.parameterLabel = QtWidgets.QLabel(form)
        self.parameterLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.parameterLabel.setObjectName("parameterLabel")
        self.configGridLayout.addWidget(self.parameterLabel, 1, 0, 1, 1)
        self.dataseriesListView = QtWidgets.QListView(form)
        self.dataseriesListView.setObjectName("dataseriesListView")
        self.configGridLayout.addWidget(self.dataseriesListView, 2, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(form)
        self.nameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.configGridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.dataseriesLabel = QtWidgets.QLabel(form)
        self.dataseriesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.dataseriesLabel.setObjectName("dataseriesLabel")
        self.configGridLayout.addWidget(self.dataseriesLabel, 2, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(form)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.configGridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.samplesLabel = QtWidgets.QLabel(form)
        self.samplesLabel.setObjectName("samplesLabel")
        self.configGridLayout.addWidget(self.samplesLabel, 3, 0, 1, 1)
        self.samplesListView = QtWidgets.QListView(form)
        self.samplesListView.setObjectName("samplesListView")
        self.configGridLayout.addWidget(self.samplesListView, 3, 1, 1, 1)
        self.mainHorizontalLayout.addLayout(self.configGridLayout)
        self.graphicView = QtWidgets.QGraphicsView(form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicView.sizePolicy().hasHeightForWidth())
        self.graphicView.setSizePolicy(sizePolicy)
        self.graphicView.setObjectName("graphicView")
        self.mainHorizontalLayout.addWidget(self.graphicView)
        self.verticalLayout.addLayout(self.mainHorizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Form"))
        self.presetsLabel.setText(_translate("form", "Presets"))
        self.parameterLabel.setText(_translate("form", "Parameter"))
        self.nameLabel.setText(_translate("form", "Name"))
        self.dataseriesLabel.setText(_translate("form", "Data Series"))
        self.samplesLabel.setText(_translate("form", "Samples"))

from gui.ressources import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    ui = Ui_form()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec_())

